### ISSUE TITLE
humbly request, when I'm trying to run attention_visualization.py 

### ISSUE THREAD

**Issue by poult-lab** [YapengTian/AVE-ECCV18#24]
Thank you did fantastic research.
I used pytorch 1.7.1 Since  I have to follow the version of cuda. I got this error, could you give some tips about which code's part I should modify.

The dataset contains 4143 samples
402
Traceback (most recent call last):
  File "attention_visualization.py", line 90, in <module>
    h_x = att_model(audio_inputs, video_inputs)
  File "/home/jiang/anaconda3/envs/hw/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jiang/桌面/AVE-ECCV18-master/models.py", line 68, in forward
    self.lstm_video.flatten_parameters()
  File "/home/jiang/anaconda3/envs/hw/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 117, in flatten_parameters
    if len(self._flat_weights) != len(self._flat_weights_names):
  File "/home/jiang/anaconda3/envs/hw/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'LSTM' object has no attribute '_flat_weights'

**Comment by YapengTian** [comment]
The code was implemented using  Pytorch-0.3.0. So, you might change your pytorch version for running the code.

**Comment by poult-lab** [comment]
Thank you for your replying.

**Comment by poult-lab** [comment]
Hello author, sorry to bother you again. Because my GPU doesn't support Cuba below 11. So I can't change to PyTorch0.3. Do you know some method to figure out this problem?

**Comment by poult-lab** [comment]
Even though I changed torch version to solve this problem, I still hope someone can solve this problem base on the more recent version of pytorch.
